server:
  port: 10011
#spring:
#  datasource:
#    driver-class-name:
#    url: jdbc:mysql://localhost:3306/Person
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    open-in-view: false